# Generated by Django 6.0.6 on 2026-06-09 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_professionnel', models.CharField(blank=True, max_length=200)),
                ('resume', models.TextField(blank=True)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('niveau_carriere', models.CharField(choices=[('etudiant', 'Étudiant'), ('junior', 'Junior'), ('intermediaire', 'Intermédiaire'), ('senior', 'Senior')], default='etudiant', max_length=20)),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('est_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=200)),
                ('etablissement', models.CharField(max_length=200)),
                ('domaine', models.CharField(blank=True, max_length=200)),
                ('annee', models.CharField(blank=True, max_length=10)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_techniques', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEmployabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('points_forts', models.JSONField(default=list)),
                ('points_faibles', models.JSONField(default=list)),
                ('recommandations', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_employabilite', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='profiles.profil')),
            ],
        ),
    ]
