# Generated by Django 6.0.6 on 2026-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='annee',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
