# Generated by Django 6.0.6 on 2026-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_formation_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreemployabilite',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
    ]
