# Generated by Django 6.0.6 on 2026-06-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_scoreemployabilite_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
