# Generated by Django 6.0.6 on 2026-06-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('type_opportunite', models.CharField(choices=[('emploi', 'Emploi'), ('stage', 'Stage'), ('bourse', 'Bourse'), ('hackathon', 'Hackathon'), ('bootcamp', 'Bootcamp')], max_length=20)),
                ('entreprise_ou_org', models.CharField(max_length=200)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('competences_requises', models.JSONField(default=list)),
                ('lien', models.URLField(blank=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-created_at'],
            },
        ),
    ]
