# Generated by Django 6.0.6 on 2026-06-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_objectif', models.CharField(max_length=200)),
                ('competences_acquises', models.JSONField(default=list)),
                ('competences_manquantes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='profiles.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_30_jours', models.JSONField(default=list)),
                ('plan_60_jours', models.JSONField(default=list)),
                ('plan_90_jours', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objectif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='matching.objectifcarriere')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('competences_acquises', models.JSONField(default=list)),
                ('competences_manquantes', models.JSONField(default=list)),
                ('explication', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_matching', to='opportunities.opportunite')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_matching', to='profiles.profil')),
            ],
            options={
                'verbose_name': 'Score Matching',
                'unique_together': {('profil', 'opportunite')},
            },
        ),
    ]
